"""Facial attribute estimation, accessory detection, and image transformation backends."""
import sys

if __name__ == "src.attributes" and "attributes" not in sys.modules:
    sys.modules["attributes"] = sys.modules["src.attributes"]
elif __name__ == "attributes" and "src.attributes" not in sys.modules:
    sys.modules["src.attributes"] = sys.modules["attributes"]

from ._lock import _lock_for
from .transformers import (
    colorize_frame,
    maybe_colorize,
    apply_geometric_transform,
    apply_intensity_transform,
    apply_enhance,
    apply_sharpen,
    apply_color_correct,
    apply_denoise,
    apply_bilateral_filter,
    apply_wavelet_denoise,
    apply_image_op,
    run_3d_reconstruction,
    run_age_progression,
    _margin_align,
    fairface_landmarks_from_mediapipe,
    align_face_with_landmarks,
    _estimate_roll_angle,
    _rotate_region,
)
from .race import (
    _softmax,
    _format_race_label,
    _fairface_forward,
    fairface_probabilities,
    fairface_race_label,
    fairface_gender_label,
    fairface_age_label,
    predict_race_fairface,
    deepface_probabilities,
    predict_race_deepface,
)
from .age import (
    caffe_probabilities,
    predict_age_caffe,
    crop_face_dex,
    dex_age_estimate,
    format_dex_age,
    predict_age_dex,
    mivolo_estimate,
    mivolo_age_estimate,
    predict_age_mivolo,
    predict_age_fairface,
    MiVOLOInference,
)
from .gender import (
    predict_gender_caffe,
    predict_gender_mivolo,
    predict_gender_fairface,
    predict_gender_deepface,
)
from .emotion import (
    predict_emotion_dan,
    predict_emotion_mini_xception,
    predict_emotion_ferplus,
    predict_emotion_hsemotion,
    audio_frame_to_mono_float,
    classify_voice_arousal,
    _emotion_arousal_category,
    fuse_voice_and_emotion,
    VoiceFaceFusion,
)
from .accessories import (
    predict_texture_artifact_score,
    predict_glasses_mobilenet,
    predict_mask_mobilenetv2,
    predict_hair_color_colorimetric,
    predict_eye_color_colorimetric,
)

__all__ = [
    "_lock_for",
    "colorize_frame",
    "maybe_colorize",
    "apply_geometric_transform",
    "apply_intensity_transform",
    "apply_enhance",
    "apply_sharpen",
    "apply_color_correct",
    "apply_denoise",
    "apply_bilateral_filter",
    "apply_wavelet_denoise",
    "apply_image_op",
    "run_3d_reconstruction",
    "run_age_progression",
    "_margin_align",
    "fairface_landmarks_from_mediapipe",
    "align_face_with_landmarks",
    "_estimate_roll_angle",
    "_rotate_region",
    "_softmax",
    "_format_race_label",
    "_fairface_forward",
    "fairface_probabilities",
    "fairface_race_label",
    "fairface_gender_label",
    "fairface_age_label",
    "predict_race_fairface",
    "deepface_probabilities",
    "predict_race_deepface",
    "caffe_probabilities",
    "predict_age_caffe",
    "crop_face_dex",
    "dex_age_estimate",
    "format_dex_age",
    "predict_age_dex",
    "mivolo_estimate",
    "mivolo_age_estimate",
    "predict_age_mivolo",
    "predict_age_fairface",
    "MiVOLOInference",
    "predict_gender_caffe",
    "predict_gender_mivolo",
    "predict_gender_fairface",
    "predict_gender_deepface",
    "predict_emotion_dan",
    "predict_emotion_mini_xception",
    "predict_emotion_ferplus",
    "predict_emotion_hsemotion",
    "audio_frame_to_mono_float",
    "classify_voice_arousal",
    "_emotion_arousal_category",
    "fuse_voice_and_emotion",
    "VoiceFaceFusion",
    "predict_texture_artifact_score",
    "predict_glasses_mobilenet",
    "predict_mask_mobilenetv2",
    "predict_hair_color_colorimetric",
    "predict_eye_color_colorimetric",
]
